name: Cleanup

on:
  workflow_call:

jobs:

  cleanup:

    runs-on: ubuntu-latest

    steps:

      - name: Cleanup
        run: |
          echo "Cleaning workspace..."
          rm -rf ./*
          echo "Done"