name: Detect Stack

on:
  workflow_call:
    outputs:
      stack:
        value: ${{ jobs.detect.outputs.stack }}

jobs:
  detect:

    runs-on: ubuntu-latest

    outputs:
      stack: ${{ steps.detect.outputs.stack }}

    steps:

      - uses: actions/checkout@v4

      - id: detect
        run: |

          if [ -f pom.xml ]; then
            echo "stack=java-maven" >> $GITHUB_OUTPUT

          elif [ -f build.gradle ] || [ -f build.gradle.kts ]; then
            echo "stack=java-gradle" >> $GITHUB_OUTPUT

          elif [ -f package.json ]; then
            echo "stack=node" >> $GITHUB_OUTPUT

          else
            echo "Unknown stack"
            exit 1
          fi

      - run: echo "Detected = ${{ steps.detect.outputs.stack }}"