name: Smart CI

on:
  workflow_call:

jobs:

  detect:

    runs-on: ubuntu-latest

    outputs:
      stack: ${{ steps.detect.outputs.stack }}

    steps:

      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Verify files
        run: ls -la

      - id: detect
        run: |

          if [ -f pom.xml ]; then
            echo "stack=java-maven" >> $GITHUB_OUTPUT

          elif [ -f build.gradle ] || [ -f build.gradle.kts ]; then
            echo "stack=java-gradle" >> $GITHUB_OUTPUT

          elif [ -f package.json ]; then
            echo "stack=node" >> $GITHUB_OUTPUT

          else
            echo "ERROR: No known project found"
            exit 1
          fi

      - name: Show detected stack
        run: echo "STACK = ${{ steps.detect.outputs.stack }}"