name: Smart CI

on:
  workflow_call:

jobs:


  detect:

    runs-on: ubuntu-latest

    outputs:
      stack: ${{ steps.detect.outputs.stack }}

    steps:

      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Detect project type
        id: detect
        run: |

          echo "Scanning repository files..."
          ls -la

          if [ -f pom.xml ]; then
            echo "stack=java-maven" >> $GITHUB_OUTPUT

          elif [ -f build.gradle ] || [ -f build.gradle.kts ]; then
            echo "stack=java-gradle" >> $GITHUB_OUTPUT

          elif [ -f package.json ]; then
            echo "stack=node" >> $GITHUB_OUTPUT

          else
            echo "ERROR: Unknown Stack"
            exit 1
          fi

      - name: Show detected stack
        run: echo "Detected Stack = ${{ steps.detect.outputs.stack }}"


  build:

    needs: detect
    runs-on: ubuntu-latest

    steps:

      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Setup Java (Maven)
        if: needs.detect.outputs.stack == 'java-maven'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Maven
        if: needs.detect.outputs.stack == 'java-maven'
        run: mvn clean package -DskipTests

      - name: Upload Maven Artifact
        if: needs.detect.outputs.stack == 'java-maven'
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Setup Java (Gradle)
        if: needs.detect.outputs.stack == 'java-gradle'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Gradle
        if: needs.detect.outputs.stack == 'java-gradle'
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Upload Gradle Artifact
        if: needs.detect.outputs.stack == 'java-gradle'
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

      - name: Setup Node
        if: needs.detect.outputs.stack == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Build Node
        if: needs.detect.outputs.stack == 'node'
        run: |
          npm ci
          npm run build

  docker:

    needs:
      - detect
      - build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Download Build Artifact
        if: needs.detect.outputs.stack != 'node'
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract repo name
        id: repo
        run: |
          echo "repo_name=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo.outputs.repo_name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo.outputs.repo_name }}:${{ github.sha }}

  cleanup:

    needs:
      - detect
      - build
      - docker

    if: always()

    runs-on: ubuntu-latest

    steps:

      - name: Cleanup Workspace
        run: |
          echo "Cleaning workspace..."
          rm -rf ./*
          echo "Cleanup completed."